### ISSUE TITLE
Driver got stuck in a loop of session renewal and expiration

### ISSUE THREAD

**Issue by angl** [snowflakedb/gosnowflake#246]
### Issue description
A query sent through the driver got stuck in what seems to be a loop between session renewal and expiration. It has so far only happened once, so it's unclear how to reproduce it. I'm not sure it's a driver bug (could potentially be a server side bug), but the fact that the driver would get stuck in such a recursive pattern (see the attached backtrace) is worrisome.

### Example code
```go
// we use sqlx to wrap around go's sql
db := sqlx.Open("snowflake", some_connect_string)
conn, _ := db.Conn(ctx)
conn.ExecContext(ctx, "BEGIN NAME tx")
conn.QueryContext(ctx, "some query")
conn.ExecContext(ctx, "COMMIT")
conn.Close()
// The db object is persistent and reused for other queries in the future. But every time we would allocate a new connection object from it through "db.Conn(ctx)".
```

Note that only one such query is stuck. Other queries issued through the same sql.DB object (but through different sql.Connection objects) are running fine. So I suspect it is caused by one particular faulty session.

### Error log
Here is the backtrace of the goroutine that got stuck.
```
goroutine 6386537 [select, 1 minutes]:
observe/vendor/github.com/snowflakedb/gosnowflake.retryHTTP(0xf9cd40, 0xc001b379b0, 0xf87c00, 0xc0001d92c0, 0xe49530, 0xd9d667, 0x4, 0xc0000fdb00, 0x899, 0xc001b37ad0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/retry.go:203 +0x414
observe/vendor/github.com/snowflakedb/gosnowflake.postRestful(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a0f200, 0x899, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:90 +0xf2
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000ce0900, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:147 +0x4ab
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc001698600, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000d0e4b0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000a686f0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000a68a80, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc00170c8d0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc0002ca4b0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000a93770, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000b9a060, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000cb0ab0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000fd2030, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000f74000, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000d0ec30, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000ce1770, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc0002ca6f0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000d5af00, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000ce1800, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000b9bb60, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000a696e0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000d5a8a0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc0002cac30, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQueryHelper(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc0008fedb0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:166 +0xd4a
observe/vendor/github.com/snowflakedb/gosnowflake.postRestfulQuery(0xf9cd40, 0xc001b379b0, 0xc000504a80, 0xc000a243b8, 0xc001b37ad0, 0xc00047af50, 0x69, 0x70, 0x0, 0xc000741500, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/restful.go:114 +0x183
observe/vendor/github.com/snowflakedb/gosnowflake.(*snowflakeConn).exec(0xc0007b3800, 0xf9cd40, 0xc001b379b0, 0xc0008fed80, 0x24, 0x0, 0x15a4638, 0x0, 0x0, 0xc00027f980, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/connection.go:102 +0x37e
observe/vendor/github.com/snowflakedb/gosnowflake.(*snowflakeConn).ExecContext(0xc0007b3800, 0xf9cd40, 0xc001b379b0, 0xc0008fed80, 0x24, 0x15a4638, 0x0, 0x0, 0xc672c0, 0xc0002efad0, ...)
	/home/dev/observe/code/go/src/observe/vendor/github.com/snowflakedb/gosnowflake/connection.go:205 +0xf8
observe/tracing/sql.(*Conn).ExecContext.func1(0xc001b37a40, 0xdac01c, 0x14, 0xc672c0)
	/home/dev/observe/code/go/src/observe/tracing/sql/sql.go:262 +0x72
observe/tracing/sql/opentracing.(*tracer).InstrumentExec(0x15a4638, 0xf9cd40, 0xc001b379b0, 0xc0003507e0, 0xc0008fed80, 0x24, 0xc54b80, 0xc00027f740, 0xc0008faaa0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/tracing/sql/opentracing/tracer.go:133 +0x157
observe/tracing/sql.(*Conn).ExecContext(0xc000c8e780, 0xf9cd40, 0xc001b379b0, 0xc0008fed80, 0x24, 0x15a4638, 0x0, 0x0, 0x0, 0x0, ...)
	/home/dev/observe/code/go/src/observe/tracing/sql/sql.go:261 +0x2dc
database/sql.ctxDriverExec(0xf9cd40, 0xc001b379b0, 0x7f2b7a014d60, 0xc000c8e780, 0x0, 0x0, 0xc0008fed80, 0x24, 0x15a4638, 0x0, ...)
	/usr/local/src/database/sql/ctxutil.go:31 +0x233
database/sql.(*DB).execDC.func2()
	/usr/local/src/database/sql/sql.go:1467 +0x1db
database/sql.withLock(0xf8b980, 0xc000579880, 0xc000706b70)
	/usr/local/src/database/sql/sql.go:3097 +0x63
database/sql.(*DB).execDC(0xc000490300, 0xf9cd40, 0xc001b379b0, 0xc000579880, 0xc0002ef8a0, 0xc0008fed80, 0x24, 0x0, 0x0, 0x0, ...)
	/usr/local/src/database/sql/sql.go:1462 +0x47d
database/sql.(*Conn).ExecContext(0xc001b37a10, 0xf9cd40, 0xc001b379b0, 0xc0008fed80, 0x24, 0x0, 0x0, 0x0, 0xe4aad8, 0xc000706d08, ...)
	/usr/local/src/database/sql/sql.go:1767 +0xef
observe/sched.runTask(0xf9cd40, 0xc001b379b0, 0xc000234960, 0xc0002426e0, 0x17, 0xf881e0, 0xc001b378f0, 0x0, 0xe9111baf6bda74e2, 0x6402e7bc60f3d4bf, ...)
	/home/dev/observe/code/go/src/observe/sched/warehouse.go:116 +0x30d
observe/sched.(*warehousePoolImpl).RunTask(0xc0000b3aa0, 0xf9cd40, 0xc001b37920, 0xf881e0, 0xc001b378f0, 0x0, 0xe9111baf6bda74e2, 0x6402e7bc60f3d4bf, 0xc0004920e0, 0xc000128c60)
	/home/dev/observe/code/go/src/observe/sched/warehousemgr.go:237 +0x5c3
created by observe/sched.(*taskManager).scheduleOne
	/home/dev/observe/code/go/src/observe/sched/taskmgr.go:475 +0x808
```

### Configuration
*Driver version (or git SHA):*
5afa7fea8224d4a581cae6383e7836f15696d4cc

*Go version:* run `go version` in your console
go version go1.12.6 linux/amd64

*Server version:* E.g. 1.90.1
3.34.2

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10
Ubuntu

**Comment by smtakeda** [comment]
We'll look into this, though, for transaction, https://golang.org/pkg/database/sql/#Conn.BeginTx should  be used to guarantee the same session is shared across the transaction.

**Comment by smtakeda** [comment]
Not reproducible in my end too, and also I've not seen this before even with other drivers.
@angl, if this happens again, please reach out the support to file a ticket and get the query ids for all queries/commands, which are available on UI. We'll find out which session failed to get renewed.
