### ISSUE TITLE
Panic when `DisableTelemetry` is set to `true`

### ISSUE THREAD

**Issue by mrduncan** [snowflakedb/gosnowflake#489]
### Issue description

`enabled` is being set to `false` on `sc.telemetry` before it is initialized: https://github.com/snowflakedb/gosnowflake/blob/v1.6.3/connection.go#L664

### Example code
```go
package main

import (
	"database/sql"
	sf "github.com/snowflakedb/gosnowflake"
)

func main() {
	sql.OpenDB(sf.NewConnector(&sf.SnowflakeDriver{}, sf.Config{
		Account:          "account",
		User:             "user",
		Password:         "password",
		Database:         "database",
		DisableTelemetry: true,
	})).Query("SELECT 1")
}
```

### Error log
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x138ba79]

goroutine 1 [running]:
github.com/snowflakedb/gosnowflake.buildSnowflakeConn({_, _}, {{0x149392e, 0x7}, {0x149161a, 0x4}, {0x1494e16, 0x8}, {0x1494b1e, 0x8}, ...})
	/Users/matt/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.3/connection.go:664 +0x279
github.com/snowflakedb/gosnowflake.SnowflakeDriver.OpenWithConfig({}, {_, _}, {{0x149392e, 0x7}, {0x149161a, 0x4}, {0x1494e16, 0x8}, {0x1494b1e, ...}, ...})
	/Users/matt/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.3/driver.go:32 +0xc8
github.com/snowflakedb/gosnowflake.Connector.Connect({{0x1570528, 0x1862158}, {{0x149392e, 0x7}, {0x149161a, 0x4}, {0x1494e16, 0x8}, {0x1494b1e, 0x8}, ...}}, ...)
	/Users/matt/go/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.3/connector.go:34 +0x105
database/sql.(*DB).conn(0xc000119d40, {0x1575070, 0xc00011c000}, 0x1)
	/usr/local/Cellar/go/1.17.2/libexec/src/database/sql/sql.go:1364 +0x7ac
database/sql.(*DB).query(0xc0001eda58, {0x1575070, 0xc00011c000}, {0x14948e6, 0x8}, {0x0, 0x0, 0x0}, 0x40)
	/usr/local/Cellar/go/1.17.2/libexec/src/database/sql/sql.go:1695 +0x5d
database/sql.(*DB).QueryContext(0x1570d98, {0x1575070, 0xc00011c000}, {0x14948e6, 0x8}, {0x0, 0x0, 0x0})
	/usr/local/Cellar/go/1.17.2/libexec/src/database/sql/sql.go:1674 +0xdf
database/sql.(*DB).Query(...)
	/usr/local/Cellar/go/1.17.2/libexec/src/database/sql/sql.go:1691
main.main()
	/Users/matt/code/scratch/sf.go:15 +0x155
exit status 2
```

### Configuration
*Driver version (or git SHA):* v1.6.3

*Go version:* go version go1.17.2 darwin/amd64

*Client OS:* macOS

**Comment by sfc-gh-jbahk** [comment]
Hi, can you raise a ticket with our support team? Thank you.

**Comment by mrduncan** [comment]
Unfortunately the only account I have access to is self-service which isn't being given access to the support portal.

**Comment by sfc-gh-jbahk** [comment]
This has been addressed and will be available in the next release.
