### ISSUE TITLE
SNOW-556791: Async query with cancelable context causing app panic

### ISSUE THREAD

**Issue by satishbhor** [snowflakedb/gosnowflake#557]
Steps:
```
ctx, cancel := context.WithCancel(context.Background())
sfCtx := sf.WithAsyncMode(ctx)
r,e := db.QueryWithContext(sfCtx)
cancel()
```

Seems like runAsync method in connection.go closing error channel twice in case error is not nil

```
       defer close(errChannel)
	token, _, _ := sr.TokenAccessor.GetTokens()
	headers[headerAuthorizationKey] = fmt.Sprintf(headerSnowflakeToken, token)
	resp, err := sr.FuncGet(ctx, sr, URL, headers, timeout)
	if err != nil {
		logger.WithContext(ctx).Errorf("failed to get response. err: %v", err)
		sfError.Message = err.Error()
		errChannel <- sfError
		close(errChannel)
		return err
	}
```
	

```
ERRO[0025]monitoring.go:219 gosnowflake.(*snowflakeConn).getQueryResultResp failed to get response. err: context canceled 
ERRO[0025]monitoring.go:237 gosnowflake.(*snowflakeConn).rowsForRunningQuery error: context canceled                      
ERRO[0027]connection.go:549 gosnowflake.getAsync failed to get response. err: context canceled 
panic: close of closed channel

goroutine 60 [running]:
github.com/snowflakedb/gosnowflake.getAsync(0x1e47880, 0xc0006af6b0, 0xc000876240, 0xc000b223f0, 0xc000b65320, 0x13a52453c0000, 0xc00089e410, 0xc00039d440, 0xc000103500, 0x1e24e40, ...)
        /opt/go_modules/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.5/connection.go:553 +0x719
created by github.com/snowflakedb/gosnowflake.postRestfulQueryHelper
        /opt/go_modules/pkg/mod/github.com/snowflakedb/gosnowflake@v1.6.5/restful.go:267 +0x1214
```

**Comment by sfc-gh-dszmolka** [comment]
thank you for submitting this issue with us and providing the details! indeed this was a valid bug up to and including `v1.6.8` of the connector, but it has been fixed with pr #568 , carried by release `v1.6.9`
