### ISSUE TITLE
SNOW-567081: Upgrade of the Terraform SF provider from 0.25.36 --> 0.28.6 causes the plugin to crash

### ISSUE THREAD

**Issue by melvinRspectrumio** [snowflakedb/gosnowflake#566]
### Issue description
When we do a `terraform plan` the plugin should not crash.

### Example code
```go
terraform {
  required_providers {
    snowflake = {
      source  = "chanzuckerberg/snowflake"
      version = "0.28.6"
    }
    aws = {
      source  = "hashicorp/aws"
      version = ">= 3.2"
    }
  }
}

terrform plan

```

### Error log
```
Error: Plugin did not respond
│ 
│   with snowflake_database.client_data,
│   on sf_databases.tf line 2, in resource "snowflake_database" "client_data":
│    2: resource "snowflake_database" "client_data" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
│ Error: Request cancelled
│ 
│   with snowflake_database.solutions_data,
│   on sf_databases.tf line 6, in resource "snowflake_database" "solutions_data":
│    6: resource "snowflake_database" "solutions_data" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

goroutine 161 [running]:
time.Time.In(...)
	time/time.go:1106
github.com/snowflakedb/gosnowflake.stringToValue(0xc00002c480, {{0xc000227a10, 0xa}, 0x0, 0x0, {0xc000227a20, 0xd}, 0x0, 0x3, 0x1}, ...)
	github.com/snowflakedb/gosnowflake@v1.6.7/converter.go:227 +0xe06
github.com/snowflakedb/gosnowflake.(*snowflakeRows).Next(0xc0009dc600, {0xc00002c480, 0x9, 0xd})
	github.com/snowflakedb/gosnowflake@v1.6.7/rows.go:173 +0x4b6
github.com/luna-duclos/instrumentedsql.wrappedRows.Next({{{0x139b020, 0xc000452f50}, {0x139b080, 0x1bb5578}, 0x0, 0x0}, {0x13be610, 0xc0001ac020}, {0x13aad58, 0xc0009dc600}}, ...)
	github.com/luna-duclos/instrumentedsql@v1.1.3/rows.go:52 +0x1e2
database/sql.(*Rows).nextLocked(0xc000998500)
	database/sql/sql.go:2967 +0x111
database/sql.(*Rows).Next.func1()
---
```
Add ``glog` option to your application to collect log files.

### Configuration
*Driver version (or git SHA):* 
- Installing chanzuckerberg/snowflake v0.28.6...
- Installed chanzuckerberg/snowflake v0.28.6 (self-signed, key ID 7F0296D97BDC3008)
- Installing hashicorp/aws v4.8.0..

Terraform v1.0.2

*Server version:* E.g. 1.90.1
You may get the server version by running a query:
```
SELECT CURRENT_VERSION();

6.9.0

```

*Client OS:* E.g. Debian 8.1 (Jessie), Windows 10
This is using Terraform

**Comment by sfc-gh-dszmolka** [comment]
should be fixed with #571 , closing this issue
