### ISSUE TITLE
SNOW-612798: Test for goroutine leaks.

### ISSUE THREAD

**Issue by maksenius** [snowflakedb/gosnowflake#588]
### Issue description
Test with check leaks failed.
Using library for test "go.uber.org/goleak"
Errors are: `internal/poll.runtime_pollWait` and `net/http.(*persistConn).writeLoop` 

### Example code
```go
func TestQuery(t *testing.T) {
	defer goleak.VerifyNone(t)

	connection := os.Getenv("SNOWFLAKE_CONNECTION")
	ctx := context.Background()

	db, err := sql.Open("snowflake", connection)
	if err != nil {
		t.Error(err)
	}

	defer db.Close()

	err = db.PingContext(ctx)
	if err != nil {
		t.Error(err)
	}

	_, err = db.Exec(query)
	if err != nil {
		t.Error(err)
	}
}
```

### Error log
```
    leaks.go:78: found unexpected goroutines:
        [Goroutine 35 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
        goroutine 35 [IO wait]:
        internal/poll.runtime_pollWait(0x7f0bdddfb740, 0x72)
        	/usr/local/go/src/runtime/netpoll.go:302 +0x89
        internal/poll.(*pollDesc).wait(0xc000460400?, 0xc00064c000?, 0x0)
        	/usr/local/go/src/internal/poll/fd_poll_runtime.go:83 +0x32
        internal/poll.(*pollDesc).waitRead(...)
        	/usr/local/go/src/internal/poll/fd_poll_runtime.go:88
        internal/poll.(*FD).Read(0xc000460400, {0xc00064c000, 0x1847, 0x1847})
        	/usr/local/go/src/internal/poll/fd_unix.go:167 +0x25a
        net.(*netFD).Read(0xc000460400, {0xc00064c000?, 0xc000a461c0?, 0xc00064c00d?})
        	/usr/local/go/src/net/fd_posix.go:55 +0x29
        net.(*conn).Read(0xc000118018, {0xc00064c000?, 0x0?, 0x0?})
        	/usr/local/go/src/net/net.go:183 +0x45
        crypto/tls.(*atLeastReader).Read(0xc0005cca38, {0xc00064c000?, 0x0?, 0x0?})
        	/usr/local/go/src/crypto/tls/conn.go:784 +0x3d
        bytes.(*Buffer).ReadFrom(0xc0001dacf8, {0x1109fc0, 0xc0005cca38})
        	/usr/local/go/src/bytes/buffer.go:204 +0x98
        crypto/tls.(*Conn).readFromUntil(0xc0001daa80, {0x110cca0?, 0xc000118018}, 0x4e?)
        	/usr/local/go/src/crypto/tls/conn.go:806 +0xe5
        crypto/tls.(*Conn).readRecordOrCCS(0xc0001daa80, 0x0)
        	/usr/local/go/src/crypto/tls/conn.go:613 +0x116
        crypto/tls.(*Conn).readRecord(...)
        	/usr/local/go/src/crypto/tls/conn.go:581
        crypto/tls.(*Conn).Read(0xc0001daa80, {0xc000a52000, 0x1000, 0x0?})
        	/usr/local/go/src/crypto/tls/conn.go:1284 +0x16f
        net/http.(*persistConn).Read(0xc00081c240, {0xc000a52000?, 0xc00067faa0?, 0xc000082d30?})
        	/usr/local/go/src/net/http/transport.go:1929 +0x4e
        bufio.(*Reader).fill(0xc0007cd920)
        	/usr/local/go/src/bufio/bufio.go:106 +0x103
        bufio.(*Reader).Peek(0xc0007cd920, 0x1)
        	/usr/local/go/src/bufio/bufio.go:144 +0x5d
        net/http.(*persistConn).readLoop(0xc00081c240)
        	/usr/local/go/src/net/http/transport.go:2093 +0x1ac
        created by net/http.(*Transport).dialConn
        	/usr/local/go/src/net/http/transport.go:1750 +0x173e
        
         Goroutine 36 in state select, with net/http.(*persistConn).writeLoop on top of the stack:
        goroutine 36 [select]:
        net/http.(*persistConn).writeLoop(0xc00081c240)
        	/usr/local/go/src/net/http/transport.go:2392 +0xf5
        created by net/http.(*Transport).dialConn
        	/usr/local/go/src/net/http/transport.go:1751 +0x1791
        ]
```

### Configuration
*Driver version (or git SHA):v1.6.10*

*Go version:1.18*

*Server version:6.18.3*

*Client OS:Linux Mint 20.1*

**Comment by sfc-gh-dszmolka** [comment]
thank you for raising this issue with us! seems to be resolved in the meantime with #660 , so closing this issue.
if you feel this is still an issue, please reopen it or commend and I'll reopen it for you.
